# Generated by Django 5.1.1 on 2024-11-15 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadHunter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("permissions", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headhunter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("task", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "headhunter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headhunters.headhunter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")], max_length=50
                    ),
                ),
                (
                    "headhunter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headhunters.headhunter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.JSONField()),
                ("experience", models.CharField(max_length=100)),
                ("language_level", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("availability", models.CharField(max_length=100)),
                ("vehicle", models.BooleanField(default=False)),
                ("disability", models.BooleanField(default=False)),
                ("search_date", models.DateTimeField(auto_now_add=True)),
                (
                    "headhunter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headhunters.headhunter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_date", models.DateTimeField(auto_now_add=True)),
                (
                    "headhunter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headhunters.headhunter",
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headhunters.searchfilter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualAssistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
                ("scheduled_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        max_length=50,
                    ),
                ),
                (
                    "headhunter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headhunters.headhunter",
                    ),
                ),
            ],
        ),
    ]
